/** Client view of the owner-provided Drive batch (b02).
 *
 * This module holds **no Drive file ids and no Drive URLs**. Everything it
 * renders comes from `driveGalleryManifest.json`, which is generated by
 * `scripts/build-drive-gallery.mjs` from sanitized local derivatives under
 * `public/media/drive-gallery/`. The browser never contacts Google.
 *
 * The manifest carries its own publication state, so the gate survives into the
 * bundle: while it is anything other than "published" the manifest is empty and
 * `visibleDriveGallery()` returns nothing, and an accidental merge ships no
 * media at all — not even the file ids.
 *
 * Source registry (build-only, never imported from src/):
 *   scripts/drive-gallery-source.mjs
 */
import manifest from "./driveGalleryManifest.json" with { type: "json" };

export type DriveGalleryKind = "photo" | "video";

export type DriveGalleryPublicationState = "review" | "published";

export type DriveGalleryPhoto = {
  id: string;
  kind: "photo";
  alt: string;
  /** Local sanitized derivative under /media/drive-gallery. */
  src: string;
  srcSet: { jpg: string; webp: string };
  width: number;
  height: number;
};

export type DriveGalleryVideo = {
  id: string;
  kind: "video";
  alt: string;
  /** Local sanitized H.264 MP4. */
  src: string;
  /** Poster taken from a real frame of that MP4. */
  poster: string;
  width: number;
  height: number;
};

export type DriveGalleryItem = DriveGalleryPhoto | DriveGalleryVideo;

export type DriveGalleryManifest = {
  publicationState: DriveGalleryPublicationState;
  items: DriveGalleryItem[];
};

export const driveGalleryManifest = manifest as DriveGalleryManifest;

/** Matches the one/two/three column photo grid in Gallery.tsx. */
export const DRIVE_PHOTO_SIZES =
  "(min-width: 640px) 220px, (min-width: 360px) 45vw, 90vw";

export function isDriveGalleryPublished(
  source: DriveGalleryManifest = driveGalleryManifest,
): boolean {
  return source.publicationState === "published";
}

/** Items rendered on the site. Empty unless the generated manifest itself says
 *  the batch is published. */
export function visibleDriveGallery(
  source: DriveGalleryManifest = driveGalleryManifest,
): DriveGalleryItem[] {
  if (!isDriveGalleryPublished(source)) {
    return [];
  }
  return source.items;
}

/* ------------------------------------------------------------------ *
 * Render model
 *
 * Gallery.tsx only spreads these objects onto elements, so the contract
 * (local-only sources, lazy loading, no autoplay, responsive widths) is
 * testable without a DOM.
 * ------------------------------------------------------------------ */

export type DrivePhotoView = {
  key: string;
  img: {
    src: string;
    srcSet: string;
    webpSrcSet: string;
    sizes: string;
    alt: string;
    width: number;
    height: number;
    loading: "lazy";
    decoding: "async";
  };
};

export type DriveVideoView = {
  key: string;
  video: {
    src: string;
    poster: string;
    width: number;
    height: number;
    /** Screen-reader label; <video> has no alt attribute. */
    label: string;
    controls: true;
    playsInline: true;
    preload: "none";
  };
};

export function drivePhotoView(item: DriveGalleryPhoto): DrivePhotoView {
  return {
    key: item.id,
    img: {
      src: item.src,
      srcSet: item.srcSet.jpg,
      webpSrcSet: item.srcSet.webp,
      sizes: DRIVE_PHOTO_SIZES,
      alt: item.alt,
      width: item.width,
      height: item.height,
      loading: "lazy",
      decoding: "async",
    },
  };
}

export function driveVideoView(item: DriveGalleryVideo): DriveVideoView {
  return {
    key: item.id,
    video: {
      src: item.src,
      poster: item.poster,
      width: item.width,
      height: item.height,
      label: item.alt,
      controls: true,
      playsInline: true,
      preload: "none",
    },
  };
}

export type DriveGallerySections = {
  photos: DrivePhotoView[];
  videos: DriveVideoView[];
  hasAny: boolean;
};

/** Split the already-gated item list into the two rendered sections. */
export function driveGallerySections(
  items: DriveGalleryItem[],
): DriveGallerySections {
  const photos = items
    .filter((item): item is DriveGalleryPhoto => item.kind === "photo")
    .map(drivePhotoView);
  const videos = items
    .filter((item): item is DriveGalleryVideo => item.kind === "video")
    .map(driveVideoView);
  return { photos, videos, hasAny: photos.length > 0 || videos.length > 0 };
}
